# The path to the local model directory or Hugging Face repo.
model: "Qwen3-VL-Text-30B-A3B-Instruct-6bit"

# Whether or not to train (boolean)
train: true

# The fine-tuning method: "lora", "dora", or "full".
fine_tune_type: lora

# The Optimizer with its possible inputs
optimizer: adam
optimizer_config:
   adam:
     betas: [0.9, 0.9999]
     eps: 1e-6
     bias_correction: true

# Directory with {train, valid, test}.jsonl files
data: "data"

# The PRNG seed
seed: 0

# Number of layers to fine-tune
num_layers: 48

# Minibatch size.
batch_size: 1

# Iterations to train for.
iters: 1000

# Number of validation batches, -1 uses the entire validation set.
val_batches: 0

# Adam learning rate.
learning_rate: 1e-4

# Services to report logs to (comma-separated): wandb, swanlab, or both ('wandb,swanlab').
report_to: wandb
project_name: "unslopper-finetune"

# Number of training steps between loss reporting.
steps_per_report: 1

# Number of training steps between validations.
steps_per_eval: 100000000

# Number of micro-steps to accumulate before each optimizer update.
grad_accumulation_steps: 1

# Load path to resume training with the given adapter weights.
resume_adapter_file: null

# Save/load path for the trained adapter weights.
adapter_path: "adapters"

# Save the model every N iterations.
save_every: 100

# Evaluate on the test set after training
test: false

# Number of test set batches, -1 uses the entire test set.
test_batches: 100

# Maximum sequence length.
max_seq_length: 6144

# Use gradient checkpointing to reduce memory use.
grad_checkpoint: true

# LoRA parameters can only be specified in a config file
lora_parameters:
  # The layer keys to apply LoRA to.
  # These will be applied for the last lora_layers
  keys: ["self_attn.q_proj", "self_attn.v_proj", "self_attn.k_proj", "self_attn.o_proj", "mlp.gate_proj", "mlp.switch_mlp.gate_proj", "mlp.switch_mlp.up_proj", "mlp.switch_mlp.down_proj"]
  rank: 8
  scale: 20.0
  dropout: 0.0

# Schedule can only be specified in a config file, uncomment to use.
lr_schedule:
  name: cosine_decay
  warmup: 10 # 0 for no warmup
  warmup_init: 1e-5 # 0 if not specified
  arguments: [1e-4, 990, 1e-5] # passed to scheduler

#hf_dataset:
#  path: "billsum"
#  train_split: "train[:1000]"
#  valid_split: "train[-100:]"
#  prompt_feature: "text"
#  completion_feature: "summary"